Renamed roles and added patreon info
0xDrMoe/TownofHost-Enhanced pull request #2
Opened 2023-10-05 21:57 UTC by ryuk201198

1. Renamed Assassin back to Evil Guesser
2. Renamed Vigilante back to Nice Guesser
3. Renamed Jailor to Jailer (for better english)
4. added mising patren info

2023-10-05 21:58 UTC, KingJacob105 commented
YESSSSS

2023-10-05 22:22 UTC, 0xDrMoe requested changes

2023-10-05 22:22 UTC, 0xDrMoe commented on Modules/DevManager.cs
I'm pushing a change on this, can you pull and PR _before_ I actually commit this?

2023-10-05 22:22 UTC, 0xDrMoe commented on Resources/Data/en.json
Same with this, pls

2023-10-05 22:24 UTC, ryuk201198 commented on Modules/DevManager.cs
alr

2023-10-05 22:27 UTC, 0xDrMoe commented
have a look now

2023-10-05 22:27 UTC, 0xDrMoe commented
double check your changes are confirmed within the PR

2023-10-05 22:31 UTC, 0xDrMoe approved these changes

2023-10-05 22:31 UTC, merged

2024-07-28 13:07 UTC, Ultradragon005 commented
this was CRAZY ya'll